apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hackathon
  name: {{ deployment.name }}
  namespace: default
spec:
  replicas: {{ deployment.replicas }}
  minReadySeconds: 45
  selector:
    matchLabels:
      app: {{ deployment.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ deployment.name }}
    spec:
      serviceAccountName: "ksa"
      containers:
        - name: {{ deployment.name }}
          image: {{ deployment.image }}:{{ deployment.tag }}
          imagePullPolicy: Always
          ports:
            - name: liveness-port
              containerPort: {{ deployment.port }}
          env:
            - name: TZ
              value: Asia/Dhaka
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: SMTP_HOST
              value: smtp.gmail.com
            - name: SMTP_PORT
              value: '587'
            - name: SMTP_USER
              value: sadatulislamsadi@gmail.com
            - name: SMTP_PASS
              value: tnxwjyacswrcqjqe
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: REDIS_SERVICE_HOST
                  name: main-config
            - name: REDIS_PORT
              value: '6379'
          resources:
            requests:
              cpu: 100m
              memory: "256Mi"
      volumes:
      - name: config-volume
        configMap:
          name: otel-config
          items:
          - key: config.yaml
            path: config.yaml
      restartPolicy: Always
      terminationGracePeriodSeconds: 30